auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Wanghui's blog
url: http://ceaserw.github.io/
feed: /atom.xml
author_info: <a href="http://ceaserw.github.io//">Wanghui</a>
